// <auto-generated />
using System;
using FinalProjGroup1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProjGroup1.Migrations
{
    [DbContext(typeof(StudentInfoContext))]
    partial class StudentInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProjGroup1.Models.StudentFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breakfast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dinner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lunch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentFood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breakfast = "Poptarts",
                            Dinner = "Chicken",
                            FullName = "Colby Nolasco",
                            Lunch = "Hot Pockets"
                        });
                });

            modelBuilder.Entity("FinalProjGroup1.Models.StudentGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentGame");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorName = "NinjaKiwi",
                            Genre = "Strategy",
                            Title = "Bloons TD 6",
                            Version = "28.3"
                        });
                });

            modelBuilder.Entity("FinalProjGroup1.Models.StudentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2021, 12, 3, 14, 40, 32, 805, DateTimeKind.Local).AddTicks(936),
                            FullName = "Zach McIntosh",
                            Program = "Cyber",
                            ProgramYear = 2
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2021, 12, 3, 14, 40, 32, 806, DateTimeKind.Local).AddTicks(9882),
                            FullName = "Ben Hicks",
                            Program = "Software",
                            ProgramYear = 2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2021, 12, 3, 14, 40, 32, 807, DateTimeKind.Local).AddTicks(52),
                            FullName = "Colby Nolasco",
                            Program = "Software",
                            ProgramYear = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
